### PR TITLE
Create PlaceBeacon.arucas

### PR DESCRIPTION
**Pull request by aFriendlyPig**

### CODE REVIEW

**Comment by senseiwells** [comment]
Seems to need some more testing?

**Comment by senseiwells** [comment]
Think that it might have been an issue with creative mode, I added some fail safes, check them out if they are ok with you then I will merge.

One last thing I was thinking was maybe BuildABeacon or BeaconBuilder might be a better name? Up to you though.

**Comment by senseiwells** [comment]
bump

**Comment by aFriendlyPig** [comment]
Changes look good to me, thanks for the help with some of the edits and bugs. As for the name, I like BeaconBuilder if you want to change it to that.

**Pull request merged**
