### PR TITLE
Create utilCommands.arcuas

### PR DESCRIPTION
**Pull request by erv123**
adds a few commands that can be useful like
/entities (displays what kind and how many entities are around)
/nbt (displays full nbt of the item in hand)
/pos (displays coordinates in chat and converts them to neather / overworld coords based on which dimension the player is in)

### CODE REVIEW

**Comment by senseiwells** [comment]
Typo on ‘neather’ should be ‘nether’
If the player dies message won’t work anymore, maybe replace with print()?

**Comment by senseiwells** [comment]
Other than that it looks cool

**Comment by erv123** [comment]
why won't message work if the player dies? Is it because the player isn't the same as when the script was started? And if that's the case wouldn't that break other stuff too?

**Comment by erv123** [comment]
I tested the dying thing and it didn't break message, still replaced all me.message with print cuz why not

**Comment by senseiwells** [comment]
maybe if the player changes dimension, I forget, as long as you've tested it and it's fine then ig it's ok

**Pull request merged**
